from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'goose.views.index', name='home'),
    url(r'^accusation_deal/$', 'goose.views.accusation_deal'),
    url(r'^accusation/$', 'goose.views.accusation'),
    url(r'^add_company/$', 'goose.views.add_company'),
    url(r'^add_shop/$', 'goose.views.add_shop'),
    url(r'^add_temp/$', 'goose.views.add_temp'),
    url(r'^add_tickling/$', 'goose.views.add_tickling'),
    url(r'^add_unattuned_shop/$', 'goose.views.add_unattuned_shop'),
    url(r'^add_waiter/$', 'goose.views.add_waiter'),
    url(r'^address/$', 'goose.views.address'),
    url(r'^app_maintain/$', 'goose.views.app_maintain'),
    url(r'^approval_addcompany/$', 'goose.views.approval_addcompany'),
    url(r'^approval_addshop/$', 'goose.views.approval_addshop'),
    url(r'^approval_altercompany/$', 'goose.views.approval_altercompany'),
    url(r'^approval_altershop/$', 'goose.views.approval_altershop'),
    url(r'^company_item/$', 'goose.views.company_item'),
    url(r'^company/$', 'goose.views.company'),
    url(r'^consumer_orders/$', 'goose.views.consumer_orders'),
    url(r'^crowdfunding_orders/$', 'goose.views.crowdfunding_orders'),
    url(r'^data/$', 'goose.views.data'),
    url(r'^explain/$', 'goose.views.explain'),
    url(r'^explain_edit/$', 'goose.views.explain_edit'),
    url(r'^feereturn/$', 'goose.views.feereturn'),
    url(r'^feedback/$', 'goose.views.feedback'),
    url(r'^forget/$', 'goose.views.forget'),
    url(r'^maintain/$', 'goose.views.maintain'),
    url(r'^pay_record/$', 'goose.views.pay_record'),
    url(r'^purse/$', 'goose.views.purse'),
    url(r'^refund_record/$', 'goose.views.refund_record'),
    url(r'^unattuned_shop/$', 'goose.views.unattuned_shop'),
    url(r'^shop_item/$', 'goose.views.shop_item'),
    url(r'^sort/$', 'goose.views.sort'),
    url(r'^temp/$', 'goose.views.temp'),
    url(r'^temp_item/$', 'goose.views.temp_item'),
    url(r'^tickling/$', 'goose.views.tickling'),
    url(r'^waiter_bill/$', 'goose.views.waiter_bill'),
    url(r'^waiter_item/$', 'goose.views.waiter_item'),
    url(r'^waiter/$', 'goose.views.waiter'),
    url(r'^waiter_pay/$', 'goose.views.waiter_pay'),
    url(r'^informality_waiter/$', 'goose.views.informality_waiter'),

    url(r'^/', include(admin.site.urls)),
)
